#!/usr/bin/env python3

import argparse
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MESHTASTIC = ROOT / "external" / "meshtastic"
MESHCORE = ROOT / "external" / "meshcore"
BRIDGE = ROOT / "bridge"
FIRMWARE = ROOT / "firmware"
VARIANT = ROOT / "variant"

BASE_ENV = "m5stack-cardputer-adv"
TARGET_ENV = "m5stack-cardputer-adv-meshcore"

STAGE_NAME = "meshcompromise"
MESHCORE_HELPERS = [
    "AdvertDataHelpers.h",
    "AdvertDataHelpers.cpp",
    "ArduinoHelpers.h",
    "IdentityStore.h",
    "IdentityStore.cpp",
    "SimpleMeshTables.h",
    "StaticPoolPacketManager.h",
    "StaticPoolPacketManager.cpp",
]

VETO_PATCH = ROOT / "patches" / "meshtastic-tx-veto.patch"
RX_VETO_PATCH = ROOT / "patches" / "meshtastic-rx-veto.patch"
QUIET_MODEM_LOG_PATCH = ROOT / "patches" / "meshtastic-quiet-modem-log.patch"

BLACKBOX_SRC = ROOT / "test" / "blackbox"
BLACKBOX_WIRE = ROOT / "test" / "test_bridge" / "meshtastic_wire.h"
BLACKBOX_CONSTANTS = ROOT / "test" / "support" / "generated" / "meshtastic_wire_constants.h"
BLACKBOX_SKIP_HEADERS = ["meshcore_stack.h", "meshcore_radio.h", "sx1262_driver.h"]
BLACKBOX_HEADERS = [
    FIRMWARE / "meshcompromise" / "contact_directory.h",
    FIRMWARE / "meshcompromise" / "text_injector.h",
    FIRMWARE / "meshcompromise" / "mirror_module.h",
    FIRMWARE / "meshcompromise" / "settings_store.h",
    FIRMWARE / "meshcompromise" / "contact_store.h",
    FIRMWARE / "meshcompromise" / "ui_input.h",
]
BLACKBOX_SOURCES = [
    BRIDGE / "src" / "meshtastic" / "contact_id.cpp",
    BRIDGE / "src" / "meshtastic" / "injected_text.cpp",
    BRIDGE / "src" / "mirror.cpp",
    BRIDGE / "src" / "settings.cpp",
    BRIDGE / "src" / "lora_profile.cpp",
    FIRMWARE / "meshcompromise" / "contact_directory.cpp",
    FIRMWARE / "meshcompromise" / "text_injector.cpp",
    FIRMWARE / "meshcompromise" / "mirror_module.cpp",
    FIRMWARE / "meshcompromise" / "settings_store.cpp",
    FIRMWARE / "meshcompromise" / "contact_store.cpp",
    FIRMWARE / "meshcompromise" / "ui_input.cpp",
]

TEMPLATE = """; generated by scripts/prepare_firmware.py, do not edit
[env:{target}]
extends = env:{base}
build_flags =
\t${{env:{base}.build_flags}}
\t-DMESHCOMPROMISE=1
\t-DRADIOLIB_GODMODE=1
\t-DMESHTASTIC_EXCLUDE_WEBSERVER=1
\t-Isrc/{stage}/include
\t-Isrc/{stage}/meshcore
\t-Isrc/{stage}/ed25519
build_src_filter =
\t${{env:{base}.build_src_filter}}
\t-<platform/extra_variants/m5stack_cardputer_adv/variant.cpp>
\t+<{stage}/>
"""


def check_layout() -> None:
    missing = [p for p in (MESHTASTIC / "platformio.ini", MESHCORE / "library.json") if not p.exists()]
    if missing:
        names = ", ".join(str(p) for p in missing)
        sys.exit(f"missing submodule content: {names}\nrun: git submodule update --init --depth 1")


def apply_patch(patch: pathlib.Path):
    """Apply patch to the meshtastic submodule unless already applied. Returns (ok, status)."""
    if not patch.exists():
        return False, "missing %s" % patch

    already = subprocess.run(["git", "apply", "--reverse", "--check", str(patch)], cwd=MESHTASTIC,
                             capture_output=True)
    if already.returncode == 0:
        return True, "already present"

    applied = subprocess.run(["git", "apply", str(patch)], cwd=MESHTASTIC, capture_output=True, text=True)
    if applied.returncode != 0:
        return False, applied.stderr.strip()

    return True, "applied"


def apply_tx_veto() -> str:
    ok, status = apply_patch(VETO_PATCH)
    if not ok:
        sys.exit(
            "cannot apply %s\n%s\n"
            "Upstream changed shape. Do not ship without this interlock: the bridge would be able to\n"
            "reprogram the radio while Meshtastic starts a transmit. Re-derive the patch against\n"
            "RadioLibInterface::canSendImmediately before building." % (VETO_PATCH.name, status)
        )
    return status


def apply_rx_veto() -> str:
    ok, status = apply_patch(RX_VETO_PATCH)
    if not ok:
        print(
            "warning: could not apply %s (%s); Meshtastic's own radio interface can still steal and discard "
            "real MeshCore receive frames while the arbiter holds the lease" % (RX_VETO_PATCH.name, status),
            file=sys.stderr,
        )
        return "skipped: " + status
    return status


def apply_quiet_modem_log() -> str:
    # Cosmetic/perf-only (see the patch itself), unlike the tx-veto interlock
    # above - if upstream drifted, warn and keep going rather than blocking
    # the build over a logging nicety.
    ok, status = apply_patch(QUIET_MODEM_LOG_PATCH)
    if not ok:
        print(
            "warning: could not apply %s (%s); RadioInterface's modem-config log lines stay at "
            "LOG_INFO and will spam every Meshtastic<->MeshCore handback" % (QUIET_MODEM_LOG_PATCH.name, status),
            file=sys.stderr,
        )
        return "skipped: " + status
    return status


def stage_sources() -> pathlib.Path:
    stage = MESHTASTIC / "src" / STAGE_NAME
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    shutil.copytree(BRIDGE / "include", stage / "include")
    shutil.copytree(BRIDGE / "src", stage / "bridge")

    glue_stage = stage / "glue"
    glue_stage.mkdir()
    headers_stage = stage / "include" / STAGE_NAME
    for path in sorted((FIRMWARE / STAGE_NAME).glob("*.h")):
        shutil.copy2(path, headers_stage / path.name)
    for path in sorted((FIRMWARE / STAGE_NAME).glob("*.cpp")):
        shutil.copy2(path, glue_stage / path.name)

    shutil.copy2(VARIANT / "variant_meshcompromise.cpp", stage / "variant_meshcompromise.cpp")

    meshcore_stage = stage / "meshcore"
    meshcore_stage.mkdir()
    for path in sorted((MESHCORE / "src").glob("*.h")):
        shutil.copy2(path, meshcore_stage / path.name)
    for path in sorted((MESHCORE / "src").glob("*.cpp")):
        shutil.copy2(path, meshcore_stage / path.name)

    helpers_stage = meshcore_stage / "helpers"
    helpers_stage.mkdir()
    for name in MESHCORE_HELPERS:
        shutil.copy2(MESHCORE / "src" / "helpers" / name, helpers_stage / name)

    shutil.copytree(MESHCORE / "lib" / "ed25519", stage / "ed25519")

    return stage


def stage_blackbox_test() -> pathlib.Path:
    stage = MESHTASTIC / "test" / "test_meshcompromise"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    shutil.copy2(BLACKBOX_SRC / "test_main.cpp", stage / "test_main.cpp")
    shutil.copy2(BLACKBOX_CONSTANTS, stage / "meshtastic_wire_constants.h")

    wire = BLACKBOX_WIRE.read_text().replace('#include "generated/meshtastic_wire_constants.h"',
                                             '#include "meshtastic_wire_constants.h"')
    (stage / "meshtastic_wire.h").write_text(wire)

    headers = stage / STAGE_NAME
    headers.mkdir()
    for header in sorted((BRIDGE / "include" / STAGE_NAME).glob("*.h")):
        if header.name not in BLACKBOX_SKIP_HEADERS:
            shutil.copy2(header, headers / header.name)
    for header in BLACKBOX_HEADERS:
        shutil.copy2(header, headers / header.name)

    for source in BLACKBOX_SOURCES:
        shutil.copy2(source, stage / source.name)

    return stage


def clear_staged_sources() -> None:
    stage = MESHTASTIC / "src" / STAGE_NAME
    if stage.exists():
        shutil.rmtree(stage)


def write_env(dry_run: bool) -> pathlib.Path:
    out_dir = MESHTASTIC / "variants" / "esp32s3" / "m5stack_cardputer_adv_meshcore"
    out_file = out_dir / "platformio.ini"

    content = TEMPLATE.format(target=TARGET_ENV, base=BASE_ENV, stage=STAGE_NAME)

    if dry_run:
        print(content)
        return out_file

    out_dir.mkdir(parents=True, exist_ok=True)
    out_file.write_text(content)
    return out_file


def main() -> None:
    parser = argparse.ArgumentParser(description="Stage MeshCompromise into the Meshtastic build")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--tests-only", action="store_true")
    args = parser.parse_args()

    check_layout()

    if args.tests_only:
        print(f"transmit-veto interlock {apply_tx_veto()}")
        print(f"receive-veto interlock {apply_rx_veto()}")
        print(f"quiet-modem-log patch {apply_quiet_modem_log()}")
        clear_staged_sources()
        print(f"staged black-box test into {stage_blackbox_test()}")
        return

    if not args.dry_run:
        print(f"transmit-veto interlock {apply_tx_veto()}")
        print(f"receive-veto interlock {apply_rx_veto()}")
        print(f"quiet-modem-log patch {apply_quiet_modem_log()}")
        stage = stage_sources()
        print(f"staged sources into {stage}")

        blackbox = stage_blackbox_test()
        print(f"staged black-box test into {blackbox}")

    out_file = write_env(args.dry_run)

    if not args.dry_run:
        print(f"wrote {out_file}")
        print(f"build with: pio run -d {MESHTASTIC} -e {TARGET_ENV}")


if __name__ == "__main__":
    main()
